version: "3.8"
services:
  # app:
  #   image: next-dev
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev
  #   container_name: web
  #   restart: always
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "3000:3000"
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
